export const phoneNumber = "9454049020";

export const teamMembers = [
  {
    name: "Mr. Pawan Maurya",
    role: "CEO / Sales Director",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/04/01-1-265x300.jpg",
    className: "md:order-2",
  },
  {
    name: "Mrs. Babita Maurya",
    role: "Sales/Marketing Head",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/WhatsApp-Image-2023-04-11-at-09.18.41-288x300.jpeg",
    className: "md:order-3",
  },
];

export const slides = [
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/001.jpg",
      title: "Luxor Hand Knotted Rugs",
      description:
        "Luxury hand-knotted rugs are one of the most sought-after decor items due to their sheer elegance and opulence.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/001.jpg",
      title: "Luxor Rugs",
      description: "Elegant hand-knotted rugs for your space.",
    },
    cta: "Explore Collection",
    link: "/products/hand-knotted",
  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/008.jpg",
      title: "Hand Knotted Rugs",
      description:
        "Hand knotted rugs are also known for their luxurious feel. The intricate design and soft pile of the rug can add elegance and sophistication to any space.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/008.jpg",
      title: "Hand Knotted",
      description: "Luxurious rugs with intricate designs.",
    },
    cta: "View Modern Series",
    link: "/products/hand-knotted",
  },
  {
    desktop: {
      image: "/images/luxury_defined.jpeg",
      title: "Luxury Defined",
      description:
        "Experience the perfect harmony of tradition and innovation in every thread.",
    },
    mobile: {
      image: "/images/luxury_defined.jpeg",
      title: "Luxury Defined",
      description: "Tradition meets innovation.",
    },
    cta: "Discover More",
    link: "/luxury-collection",
  },
  {
    desktop: {
      image: "/images/hand_tuft.jpeg",
      title: "Hand Tufted Rugs",
      description:
        "Experience the perfect harmony of tradition and innovation in every thread.",
    },
    mobile: {
      image: "/images/hand_tuft.jpeg",
      title: "Hand Tufted Rugs",
      description: "Traditional craftsmanship in every thread.",
    },
    cta: "Discover More",
    link: "/products/hand-tufted",
  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/002.jpg",
      title: "Hand tufted Carpets",
      description:
        "Hand tufted carpets come in various shapes, sizes, and designs. They can be made from a wide range of materials, including wool, silk, cotton, and synthetic fibers",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/002.jpg",
      title: "Hand Tufted",
      description: "Premium carpets in various materials and designs.",
    },
    cta: "Discover More",
    link: "/products/hand-tufted",
  },
];

export const categories = [
  {
    id: 1,
    name: "Hand Knotted Rugs",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK04.jpg",
    description: "Intricately crafted traditional rugs with detailed patterns",
    slug: "products/hand-knotted",
  },
  {
    id: 2,
    name: "Hand Loom Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL07-225x300.jpg",
    description: "Contemporary rugs with subtle, minimalist designs",
    slug: "products/hand-loom",
  },
  {
    id: 3,
    name: "Hand Tufted Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/01-1-1-224x300.jpg",
    description: "Modern rugs with bold, geometric patterns",
    slug: "products/hand-tufted",
  },
  {
    id: 4,
    name: "Flat Weave Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/003-768x1028-1-224x300.jpg",
    description: "Versatile rugs perfect for high-traffic areas",
    slug: "products/flat-weave",
  },
  {
    id: 5,
    name: "Jute Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/20-1-224x300.jpg",
    description: "Eco-friendly rugs with natural textures",
    slug: "products/jute",
  },
];

export const hospitalityCollection = [
  {
    id: 1,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/701.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 4.5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 2,
    image: "	https://thephenixcarpets.com/wp-content/uploads/2023/05/702.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56112",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-054",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 3,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/703.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56113",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-055",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 4,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/704-1.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56114",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-056",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 5,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/705.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56115",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-057",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 6,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/706.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56116",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-058",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 7,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/707.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56117",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-059",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 8,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/708.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56118",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-060",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 9,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/709.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56119",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-061",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 10,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/710.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56120",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-062",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 11,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/711.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56121",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-063",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 12,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/712.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56122",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-064",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 13,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/713.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56123",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-065",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 14,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/727.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56124",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-066",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 15,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/729.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56125",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-067",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 16,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/735-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56126",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-068",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 17,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/736-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56127",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-069",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 18,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/737-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56128",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-070",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 19,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/738-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56129",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-071",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 20,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/739-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56130",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-072",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 21,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/740-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56131",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-073",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 22,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/742-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56132",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-074",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 23,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/743-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56133",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-075",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 24,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/745-1024x1024.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56134",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-076",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
];

export const luxuryCollection = [
  {
    id: "CL-05-001",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/715-1.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-04",
    reviews: [],
  },
  {
    id: "CL-05-002",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/716-1.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-05",
    reviews: [],
  },
  {
    id: "CL-05-003",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/717.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-06",
    reviews: [],
  },
  {
    id: "CL-05-004",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/718.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-07",
    reviews: [],
  },
  {
    id: "CL-05-005",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/719-300x300.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-08",
    reviews: [],
  },
  {
    id: "CL-05-006",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/720.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-09",
    reviews: [],
  },
  {
    id: "CL-05-007",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/721.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-10",
    reviews: [],
  },
  {
    id: "CL-05-08",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/722.jpg",
    name: "Luxor Collection",
    pileComposition: "100% Viscose",
    quality: "Handknotted 10/42 (95 KPSI)",
    pileHeight: "8MM",
    totalHeight: "10MM",
    size: "On Request",
    maxSize: "On Request",
    sampleSize: "2.0 x 2.0 feet",
    pileWeight: "4000 GSM/SQM",
    totalWeight: "5000 GSM/SQM",
    color: "Dk. Browm",
    styleNumber: "CL-11",
    reviews: [],
  },
];

export const productsCategoryCollection = [
  // Hand Knotted Category
  {
    id: 1,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK06-2.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.5,
    productCode: "RSM97011",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-022",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 2,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK09-2-765x1024.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.8,
    productCode: "RSM97012",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-023",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 3,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK04.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97013",
    pattern: "Classic",
    style: "Moder",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-024",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  {
    id: 16,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK07.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97014",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-025",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  {
    id: 17,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK01.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97015",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-026",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  {
    id: 18,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK02.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97016",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Knotted",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-027",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  {
    id: 19,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK03.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97017",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-028",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  {
    id: 20,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK08-1.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97018",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-029",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 21,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK10-1.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97019",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-030",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 22,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/TPC_6354.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97020",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-031",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 23,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/007.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97021",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-032",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 24,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/07.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97022",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-033",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 25,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/11.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97023",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-034",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 26,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/12.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97024",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-035",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 27,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/13.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97025",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-036",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 28,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/14-719x1024.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97026",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-037",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 29,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/19.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97027",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-038",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 30,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/20.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97028",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-039",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 31,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/24.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97029",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-040",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 32,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/08.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97030",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-041",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 33,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/016.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97031",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-042",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 34,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/101.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97032",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-043",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 35,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/110.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97033",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-044",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 36,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/108.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "RSM97034",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-045",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  // / Hand Loom Category
  {
    id: 4,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL10.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76053",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-013",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 5,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL07.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76054",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-014",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 6,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL08.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76055",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-015",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 37,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL09.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76056",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-016",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 38,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL1.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76057",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-017",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 39,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL03.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76058",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-018",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 40,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL04.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76059",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-019",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 41,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL05.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76060",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-020",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 42,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL2.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76061",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-021",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 43,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL06.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76062",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-022",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 44,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL11.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76063",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-023",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 45,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL05.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.6,
    productCode: "UD76064",
    pattern: "Plan",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Weaving",
    pileHeight: "Short pile (8 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "LPHO-BNPL-024",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  // Hand Tufted Category
  {
    id: 7,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/01-1-1-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56091",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-033",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 8,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht2-1-765x1024.jpeg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56092",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-034",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 9,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht3-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56093",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-035",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 46,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht4-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56094",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-036",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 47,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht5-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56095",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-037",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 48,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht6-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56096",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-038",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 49,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht7-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56097",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-039",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 50,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht8-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56098",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-040",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 51,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/ht9-765x1024.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.7,
    productCode: "PWM56099",
    pattern: "Graphic/Abstract",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-041",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  // Flat Weave Category
  {
    id: 10,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/001-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39049",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-086",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 11,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/003-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39050",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-087",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 12,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/012-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39051",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-088",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 52,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/009-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39052",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-089",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 53,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/FLT1153-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39053",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-090",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 54,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/010-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39054",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-091",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 55,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/011-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39055",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-092",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 56,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/004-1-765x1024.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.5,
    productCode: "RMS39056",
    pattern: "Classic/Linear",
    style: "Modern",
    material: "Wool",
    productionType: "Hand weaving",
    pileHeight: "flat pile (6 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "FLHO-WNPL-093",
    customization: "on request",
    origin: "India",
    reviews: [],
  },

  // Jute Category
  {
    id: 13,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/02-2-1024x1024.jpeg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19052",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-051",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 14,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/03-1024x1024.jpeg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19053",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-052",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 15,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/04-1024x1024.jpeg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19054",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-053",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 56,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/05-1024x1024.jpeg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19055",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-054",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 57,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/15-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19056",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-055",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 58,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/16-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19057",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-056",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 59,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/17-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19058",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-057",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 60,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/18-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19059",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-058",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 61,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/19-1-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19060",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-059",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 62,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/20-1-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19061",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-060",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 63,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/22-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19062",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-061",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
  {
    id: 64,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/23-765x1024.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "on order",
    rating: 4.4,
    productCode: "AKM19063",
    pattern: "Braided",
    style: "Modern",
    material: "Jute",
    productionType: " Hand weaving",
    pileHeight: "6 mm",
    shape: "Round",
    size: "on request",
    productId: "JTHO-BNPL-062",
    customization: "on request",
    origin: "India",
    reviews: [],
  },
];

export const categoryDescriptions = {
  "Hand Knotted": `Hand-knotted rugs are premium quality floor coverings that are handcrafted by skilled artisans. They are created by knotting individual pieces of wool or silk onto a warp and weft frame, one knot at a time. These rugs are known for their exceptional beauty, durability, and impressive colors. They are considered a true work of art and take months to complete. Hand-knotted rugs have a rich legacy that traces back to ancient Persia and the nomadic tribes of Central Asia (Bhadohi, India). Today, these rugs continue to make a statement in interior design and are cherished heirlooms that are passed down from generation to generation.`,
  "Hand Loom": `Hand loom carpets are traditional textiles that are made using traditional weaving techniques. These carpets are crafted by hand on a loom, with each thread individually woven to create intricate patterns and designs. The process of making a hand loom carpet is labor-intensive and less time-consuming, but the end result is a unique, one-of-a-kind piece that is durable and beautiful. Hand loom carpets can be made using a variety of materials, including wool, cotton, silk, and jute. These carpets are often used as a decorative element in home interiors, adding warmth and texture to a room.`,
  "Hand Tufted": `Hand tufted carpets are made by inserting yarn or wool into a backing material using a tufting gun, creating a pile. The pile is then sheared and finished to create a beautiful and durable carpet. These carpets offer unique and intricate designs for a luxurious aesthetic appeal. They are also highly customizable, allowing for various colors, patterns, and textures. Hand tufted carpets are a popular choice for both residential and commercial spaces due to their durability, ease of maintenance, and ability to withstand heavy traffic. They are also an eco-friendly option as they are made using fewer resources than traditional, woven carpets.`,
  "Flat Weave": `Flat weave rugs are a popular flooring option that are created by weaving fibers together in a flat, even pattern. They are known for their durability, flexibility and versatility in design. With a rich history in several cultures, they have become a staple in modern interior design. Flat weave rugs are often made with natural fibers such as wool, cotton or jute, but they can also be made with synthetic fibers. They are a great choice for high-traffic areas in the home, as they are easy to clean and maintain. Many designers choose flat weave rugs for their bold and vibrant colors, graphic patterns, and geometric shapes that can easily transform a space.`,
  Jute: `Jute rugs are an eco-friendly and sustainable flooring option that have been used for centuries. They are made from the fibers of the jute plant, which is known for its strength and durability. Jute rugs have a natural, earthy look and feel that can add warmth and texture to any room. They are also hypoallergenic, making them a great choice for people with allergies or sensitivities. Jute rugs come in a variety of colors, patterns, and textures, from fine to chunky weaves. They are easy to clean and maintain, making them perfect for high-traffic areas. Jute rugs are a great choice for those who want to create a stylish and sustainable home.`,
};

export const collectionsInstagramWall = [
  {
    id: 1,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/tpc03-scaled.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 2,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/tpc02-scaled.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 3,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/tpc06-1-scaled.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 4,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/tpc04-scaled.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 5,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/Untitled-1-copy.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
  {
    id: 6,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/tpc05-scaled.jpg",
    link: "https://instagram.com/the_phenix_carpet_?igshid=ZGUzMzM3NWJiOQ==",
  },
];
