export const phoneNumber = "";

export const teamMembers = [
  {
    name: "Mr. Pawan Maurya",
    role: "CEO / Sales Director",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/04/01-1-265x300.jpg",
    className: "md:order-2",
  },
  {
    name: "Mrs. Babita Maurya",
    role: "Sales/Marketing Head",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/WhatsApp-Image-2023-04-11-at-09.18.41-288x300.jpeg",
    className: "md:order-3",
  },
];

export const slides = [
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/001.jpg",
      title: "Luxor Hand Knotted Rugs",
      description:
        "Luxury hand-knotted rugs are one of the most sought-after decor items due to their sheer elegance and opulence.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/001.jpg",
      title: "Luxor Rugs",
      description: "Elegant hand-knotted rugs for your space.",
    },
    cta: "Explore Collection",
    link:"/products/hand-knotted"
  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/008.jpg",
      title: "Hand Knotted Rugs",
      description:
        "Hand knotted rugs are also known for their luxurious feel. The intricate design and soft pile of the rug can add elegance and sophistication to any space.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/008.jpg",
      title: "Hand Knotted",
      description: "Luxurious rugs with intricate designs.",
    },
    cta: "View Modern Series",
    link:"/products/hand-knotted"

  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/007.jpg",
      title: "Luxury Defined",
      description:
        "Experience the perfect harmony of tradition and innovation in every thread.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/005.jpg",
      title: "Luxury Defined",
      description: "Tradition meets innovation.",
    },
    cta: "Discover More",
    link:"/luxury-collection"

  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/004.jpg",
      title: "Turkish Hand Knots Rugs",
      description:
        "Experience the perfect harmony of tradition and innovation in every thread.",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/003.jpg",
      title: "Turkish Rugs",
      description: "Traditional craftsmanship in every thread.",
    },
    cta: "Discover More",
    link:"/products/hand-knotted"

  },
  {
    desktop: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/04/002.jpg",
      title: "Hand tufted Carpets",
      description:
        "Hand tufted carpets come in various shapes, sizes, and designs. They can be made from a wide range of materials, including wool, silk, cotton, and synthetic fibers",
    },
    mobile: {
      image: "https://thephenixcarpets.com/wp-content/uploads/2023/06/002.jpg",
      title: "Hand Tufted",
      description: "Premium carpets in various materials and designs.",
    },
    cta: "Discover More",
    link:"/products/hand-tufted"

  },
];

export const categories = [
  {
    id: 1,
    name: "Hand Knotted Rugs",
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK04.jpg",
    description: "Intricately crafted traditional rugs with detailed patterns",
    slug: "hand-knotted-rugs",
  },
  {
    id: 2,
    name: "Hand Loom Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/HL07-225x300.jpg",
    description: "Contemporary rugs with subtle, minimalist designs",
    slug: "hand-loom-rugs",
  },
  {
    id: 3,
    name: "Hand Tufted Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/01-1-1-224x300.jpg",
    description: "Modern rugs with bold, geometric patterns",
    slug: "hand-tufted-rugs",
  },
  {
    id: 4,
    name: "Flat Weave Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/003-768x1028-1-224x300.jpg",
    description: "Versatile rugs perfect for high-traffic areas",
    slug: "flat-weave-rugs",
  },
  {
    id: 5,
    name: "Jute Rugs",
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/20-1-224x300.jpg",
    description: "Eco-friendly rugs with natural textures",
    slug: "jute-rugs",
  },
];

export const hospitalityCollection = [
  {
    id: 1,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/701.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 2,
    image: "	https://thephenixcarpets.com/wp-content/uploads/2023/05/702.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 3,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/703.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 4,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/704-1.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 5,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/705.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 6,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/706.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 7,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/707.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 8,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/708.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 9,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/709.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 10,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/710.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 11,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/711.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 12,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/712.jpg",
    name: "Hospitality Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
];

export const luxuryCollection = [
  {
    id: 1,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/715-1.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 2,
    image: "	https://thephenixcarpets.com/wp-content/uploads/2023/05/716-1.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 3,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/717.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 4,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/718.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 5,
    image:
      "https://thephenixcarpets.com/wp-content/uploads/2023/05/719-300x300.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 6,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/720.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 7,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/721.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
  {
    id: 8,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/722.jpg",
    name: "Luxury Collection",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Plain/Rust",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Tufting",
    pileHeight: "Medium pile (12 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "HTHO-BNPL-053",
    customization: "on request",
    origin: "India",
  },
];

export const productsCategoryCollection = [
  // Hand Knotted Category
  {
    id: 1,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK06-2.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 5,
    productCode: "PWM56111",
    pattern: "Classic",
    style: "Modern",
    material: "Wool",
    productionType: "Hand Knotted",
    pileHeight: "Medium pile (10 mm)",
    shape: "Rectangular",
    size: "on request",
    productId: "KPHO-BNPL-022",
    customization: "on request",
    origin: "India"
  },
  {
    id: 2,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK09-2-765x1024.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.8,
    productCode: "PWM56112",
    pattern: "Geometric",
    style: "Traditional",
    material: "Silk Blend",
    productionType: "Hand Knotted",
    pileHeight: "Low pile (5 mm)",
    shape: "Round",
    size: "200x300 cm",
    productId: "KPHO-BNPL-023",
    customization: "limited",
    origin: "India"
  },
  {
    id: 3,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK04.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "PWM56113",
    pattern: "Floral",
    style: "Antique",
    material: "Pure Wool",
    productionType: "Hand Knotted",
    pileHeight: "High pile (15 mm)",
    shape: "Rectangular",
    size: "250x350 cm",
    productId: "KPHO-BNPL-024",
    customization: "full",
    origin: "India"
  },

  {
    id: 16,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK07.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "PWM56113",
    pattern: "Floral",
    style: "Antique",
    material: "Pure Wool",
    productionType: "Hand Knotted",
    pileHeight: "High pile (15 mm)",
    shape: "Rectangular",
    size: "250x350 cm",
    productId: "KPHO-BNPL-024",
    customization: "full",
    origin: "India"
  },

  {
    id: 17,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK01.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "PWM56113",
    pattern: "Floral",
    style: "Antique",
    material: "Pure Wool",
    productionType: "Hand Knotted",
    pileHeight: "High pile (15 mm)",
    shape: "Rectangular",
    size: "250x350 cm",
    productId: "KPHO-BNPL-024",
    customization: "full",
    origin: "India"
  },

  {
    id: 18,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK02.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "PWM56113",
    pattern: "Floral",
    style: "Antique",
    material: "Pure Wool",
    productionType: "Hand Knotted",
    pileHeight: "High pile (15 mm)",
    shape: "Rectangular",
    size: "250x350 cm",
    productId: "KPHO-BNPL-024",
    customization: "full",
    origin: "India"
  },
  

  {
    id: 19,
    image: "https://thephenixcarpets.com/wp-content/uploads/2023/05/HK03.jpg",
    name: "Hand Knotted Rugs",
    category: "Hand Knotted",
    availability: "on order",
    rating: 4.9,
    productCode: "PWM56113",
    pattern: "Floral",
    style: "Antique",
    material: "Pure Wool",
    productionType: "Hand Knotted",
    pileHeight: "High pile (15 mm)",
    shape: "Rectangular",
    size: "250x350 cm",
    productId: "KPHO-BNPL-024",
    customization: "full",
    origin: "India"
  },
  
  
  
  
  // Hand Loom Category
  {
    id: 4,
    image: "https://example.com/hand-loom-1.jpg",
    name: "Modern Hand Loom Rug",
    category: "Hand Loom",
    availability: "in stock",
    rating: 4.6,
    productCode: "PLM56114",
    pattern: "Striped",
    style: "Contemporary",
    material: "Cotton",
    productionType: "Hand Loom",
    pileHeight: "Flat weave",
    shape: "Rectangular",
    size: "160x230 cm",
    productId: "PLHO-BNPL-025",
    customization: "limited",
    origin: "India"
  },
  {
    id: 5,
    image: "https://example.com/hand-loom-2.jpg",
    name: "Minimalist Hand Loom Carpet",
    category: "Hand Loom",
    availability: "on order",
    rating: 4.7,
    productCode: "PLM56115",
    pattern: "Solid",
    style: "Minimalist",
    material: "Wool Blend",
    productionType: "Hand Loom",
    pileHeight: "Flat weave",
    shape: "Square",
    size: "200x200 cm",
    productId: "PLHO-BNPL-026",
    customization: "on request",
    origin: "India"
  },
  {
    id: 6,
    image: "https://example.com/hand-loom-3.jpg",
    name: "Ethnic Hand Loom Design",
    category: "Hand Loom",
    availability: "in stock",
    rating: 4.5,
    productCode: "PLM56116",
    pattern: "Geometric",
    style: "Bohemian",
    material: "Cotton and Jute",
    productionType: "Hand Loom",
    pileHeight: "Flat weave",
    shape: "Rectangular",
    size: "120x180 cm",
    productId: "PLHO-BNPL-027",
    customization: "limited",
    origin: "India"
  },
  
  // Hand Tufted Category
  {
    id: 7,
    image: "https://example.com/hand-tufted-1.jpg",
    name: "Soft Hand Tufted Rug",
    category: "Hand Tufted",
    availability: "in stock",
    rating: 4.7,
    productCode: "PTF56117",
    pattern: "Abstract",
    style: "Modern",
    material: "Acrylic Blend",
    productionType: "Hand Tufted",
    pileHeight: "Thick pile (20 mm)",
    shape: "Rectangular",
    size: "180x270 cm",
    productId: "PTHO-BNPL-028",
    customization: "on request",
    origin: "India"
  },
  {
    id: 8,
    image: "https://example.com/hand-tufted-2.jpg",
    name: "Luxurious Hand Tufted Carpet",
    category: "Hand Tufted",
    availability: "on order",
    rating: 4.9,
    productCode: "PTF56118",
    pattern: "Damask",
    style: "Classic",
    material: "New Zealand Wool",
    productionType: "Hand Tufted",
    pileHeight: "Medium pile (12 mm)",
    shape: "Round",
    size: "250x250 cm",
    productId: "PTHO-BNPL-029",
    customization: "full",
    origin: "India"
  },
  {
    id: 9,
    image: "https://example.com/hand-tufted-3.jpg",
    name: "Contemporary Hand Tufted Design",
    category: "Hand Tufted",
    availability: "in stock",
    rating: 4.6,
    productCode: "PTF56119",
    pattern: "Geometric",
    style: "Contemporary",
    material: "Polyester Blend",
    productionType: "Hand Tufted",
    pileHeight: "Low pile (8 mm)",
    shape: "Rectangular",
    size: "160x230 cm",
    productId: "PTHO-BNPL-030",
    customization: "limited",
    origin: "India"
  },
  
  // Flat Weave Category
  {
    id: 10,
    image: "https://example.com/flat-weave-1.jpg",
    name: "Classic Flat Weave Kilim",
    category: "Flat Weave",
    availability: "in stock",
    rating: 4.5,
    productCode: "PFW56120",
    pattern: "Traditional",
    style: "Ethnic",
    material: "Wool",
    productionType: "Flat Weave",
    pileHeight: "Flat weave",
    shape: "Rectangular",
    size: "120x180 cm",
    productId: "PFHO-BNPL-031",
    customization: "limited",
    origin: "India"
  },
  {
    id: 11,
    image: "https://example.com/flat-weave-2.jpg",
    name: "Modern Flat Weave Rug",
    category: "Flat Weave",
    availability: "on order",
    rating: 4.7,
    productCode: "PFW56121",
    pattern: "Geometric",
    style: "Contemporary",
    material: "Cotton",
    productionType: "Flat Weave",
    pileHeight: "Flat weave",
    shape: "Square",
    size: "200x200 cm",
    productId: "PFHO-BNPL-032",
    customization: "on request",
    origin: "India"
  },
  {
    id: 12,
    image: "https://example.com/flat-weave-3.jpg",
    name: "Minimalist Flat Weave Carpet",
    category: "Flat Weave",
    availability: "in stock",
    rating: 4.6,
    productCode: "PFW56122",
    pattern: "Solid",
    style: "Minimalist",
    material: "Jute Blend",
    productionType: "Flat Weave",
    pileHeight: "Flat weave",
    shape: "Rectangular",
    size: "150x220 cm",
    productId: "PFHO-BNPL-033",
    customization: "limited",
    origin: "India"
  },
  
  // Jute Category
  {
    id: 13,
    image: "https://example.com/jute-1.jpg",
    name: "Natural Jute Area Rug",
    category: "Jute",
    availability: "in stock",
    rating: 4.4,
    productCode: "PJT56123",
    pattern: "Braided",
    style: "Natural",
    material: "100% Jute",
    productionType: "Handwoven",
    pileHeight: "Low pile",
    shape: "Rectangular",
    size: "140x200 cm",
    productId: "PJHO-BNPL-034",
    customization: "limited",
    origin: "India"
  },
  {
    id: 14,
    image: "https://example.com/jute-2.jpg",
    name: "Eco-Friendly Jute Carpet",
    category: "Jute",
    availability: "on order",
    rating: 4.6,
    productCode: "PJT56124",
    pattern: "Herringbone",
    style: "Sustainable",
    material: "Jute and Recycled Cotton",
    productionType: "Handwoven",
    pileHeight: "Flat weave",
    shape: "Round",
    size: "180x180 cm",
    productId: "PJHO-BNPL-035",
    customization: "on request",
    origin: "India"
  },
  {
    id: 15,
    image: "https://example.com/jute-3.jpg",
    name: "Rustic Jute Floor Covering",
    category: "Jute",
    availability: "in stock",
    rating: 4.5,
    productCode: "PJT56125",
    pattern: "Natural Weave",
    style: "Rustic",
    material: "Jute",
    productionType: "Handwoven",
    pileHeight: "Low pile",
    shape: "Rectangular",
    size: "160x230 cm",
    productId: "PJHO-BNPL-036",
    customization: "limited",
    origin: "India"
  }
];
export const categoryDescriptions = {
  "Hand Knotted": `Hand-knotted rugs are premium quality floor coverings that are handcrafted by skilled artisans. They are created by knotting individual pieces of wool or silk onto a warp and weft frame, one knot at a time. These rugs are known for their exceptional beauty, durability, and impressive colors. They are considered a true work of art and take months to complete. Hand-knotted rugs have a rich legacy that traces back to ancient Persia and the nomadic tribes of Central Asia (Bhadohi, India). Today, these rugs continue to make a statement in interior design and are cherished heirlooms that are passed down from generation to generation.`,
  "Hand Loom": `Hand loom carpets are traditional textiles that are made using traditional weaving techniques. These carpets are crafted by hand on a loom, with each thread individually woven to create intricate patterns and designs. The process of making a hand loom carpet is labor-intensive and less time-consuming, but the end result is a unique, one-of-a-kind piece that is durable and beautiful. Hand loom carpets can be made using a variety of materials, including wool, cotton, silk, and jute. These carpets are often used as a decorative element in home interiors, adding warmth and texture to a room.`,
  "Hand Tufted": `Hand tufted carpets are made by inserting yarn or wool into a backing material using a tufting gun, creating a pile. The pile is then sheared and finished to create a beautiful and durable carpet. These carpets offer unique and intricate designs for a luxurious aesthetic appeal. They are also highly customizable, allowing for various colors, patterns, and textures. Hand tufted carpets are a popular choice for both residential and commercial spaces due to their durability, ease of maintenance, and ability to withstand heavy traffic. They are also an eco-friendly option as they are made using fewer resources than traditional, woven carpets.`,
  "Flat Weave": `Flat weave rugs are a popular flooring option that are created by weaving fibers together in a flat, even pattern. They are known for their durability, flexibility and versatility in design. With a rich history in several cultures, they have become a staple in modern interior design. Flat weave rugs are often made with natural fibers such as wool, cotton or jute, but they can also be made with synthetic fibers. They are a great choice for high-traffic areas in the home, as they are easy to clean and maintain. Many designers choose flat weave rugs for their bold and vibrant colors, graphic patterns, and geometric shapes that can easily transform a space.`,
  Jute: `Jute rugs are an eco-friendly and sustainable flooring option that have been used for centuries. They are made from the fibers of the jute plant, which is known for its strength and durability. Jute rugs have a natural, earthy look and feel that can add warmth and texture to any room. They are also hypoallergenic, making them a great choice for people with allergies or sensitivities. Jute rugs come in a variety of colors, patterns, and textures, from fine to chunky weaves. They are easy to clean and maintain, making them perfect for high-traffic areas. Jute rugs are a great choice for those who want to create a stylish and sustainable home.`,
};
